@startuml
'https://plantuml.com/sequence-diagram

class App {
    +{static}list : ArrayList<>
}

class ReadFile {
    +{static}readFilesNames()
}

class PrintFile {
    +{static}printTable()
}

App o--> ReadFile
App o--> PrintFile
@enduml